### ISSUE TITLE
find_package(GTest CONFIG REQUIRED)

### ISSUE THREAD

**Issue by headupinclouds** [abandonware-pjz37/gtest-pass-filename#1]
It should probably take advantage of the latest package config usage described in the Hunter gtest wiki: https://github.com/ruslo/hunter/wiki/pkg.gtest

I can update this later.

**Comment by ruslo** [comment]
Well originally it's not a Hunter example, it's a companion code for SO answer (I've added link to description: http://stackoverflow.com/a/25219861/2288008). Hunter can be added but `HUNTER_ENABLED` should be `OFF` I guess.

**Comment by headupinclouds** [comment]
Thanks for the clarification.  Not sure how I missed that.  Sorry about that.
